name: Update Counter

on:
  workflow_dispatch: # Allows manual trigger from GitHub
  repository_dispatch: # Can be triggered via external API if needed

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read Counter File
        id: read-counter
        run: |
          COUNTER=$(jq '.count' counter.json)
          echo "Current Count: $COUNTER"
          echo "count=$COUNTER" >> $GITHUB_ENV # Set as environment variable, not output

      - name: Update Counter
        run: |
          NEW_COUNT=$(( ${{ env.count }} + 1 )) # Use environment variable
          echo "{ \"count\": $NEW_COUNT }" > counter.json
          echo "Updated Count: $NEW_COUNT"

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add counter.json
          git commit -m "Update counter to $NEW_COUNT"
          git push
