name: Update Counter

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Read Counter File
        id: read-counter
        run: |
          COUNTER=$(jq '.count' counter.json)
          echo "Current Count: $COUNTER"
          echo "::set-output name=count::$COUNTER"

      - name: Update Counter
        run: |
          NEW_COUNT=$(( ${{ steps.read-counter.outputs.count }} + 1 ))
          echo "{ \"count\": $NEW_COUNT }" > counter.json
          echo "Updated Count: $NEW_COUNT"

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}
          git add counter.json
          git commit -m "Update counter to ${{ steps.read-counter.outputs.count }} + 1"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
